apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "dracula-covid19"
  namespace: "production"
  labels:
    app: dracula-covid19
    task: all
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: dracula-covid19
            task: all
          annotations:
            iam.amazonaws.com/role: k8s-dracula
        spec:
          restartPolicy: Never
          serviceAccountName: dracula
          containers:
            - name: dracula
              image: "554546661178.dkr.ecr.eu-central-1.amazonaws.com/dracula:covid-19-asdf1234"
              imagePullPolicy: Always
              command:
                - bash
                - "-c"
                - echo START;
                  exec time dracula-covid19
